### ISSUE TITLE
Jobseeker Edit Profile: Previous Project Skills not loading (Test & Merge #102 Before Me)

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#101]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Bug

### Issue Description

When editing profile. Navigation to the Education page loads up projects but the Skills input is blank even though I have entered them already.

### URL of the Page

https://www.watechwfcoalition.org/edit-profile/jobseeker/education

### Git commit hash shown on the site

a95009e

### Steps to Reproduce

1. Create an account ensuring completing at least one project entry.
2.  After completion click Avatar image
3.  Choose & Click Edit Profile
4.  On Introduction, save and continue
5.  Observe previous entered projects

### Expected Behavior

Previously entered skills to load into the skills input section

### Additional Context

![{A0048A0B-4629-4B18-80F6-6866403569EF}](https://github.com/user-attachments/assets/a5850718-f3e3-42de-bff8-1196cf50d289)

### Recommended Priority Level

High

**Comment by cfa-jonathan** [comment]
This should be resolved by the following pull request: https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/101

**Comment by theGaryLarson** [comment]
LGTM Closed
