### ISSUE TITLE
Jobseeker Edit Profile: Education enrollment status not loading into input (Test & Merge #77 Before Me)

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#102]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Bug

### Issue Description

After creating an account and choosing Edit profile. Once the education page loads "What is your enrollment status?" is left blank even though I had entered graduated/completed previously on account creation.

### URL of the Page

https://www.watechwfcoalition.org/edit-profile/jobseeker/education

### Git commit hash shown on the site

a95009e

### Steps to Reproduce

1. Create and complete an account ensuring filling in a complete Education history entry.
2. Choose Edit profile from the profile menu
3. At introduction, save and continue
4.  Observe Education entry on the edit profile education page.

### Expected Behavior

For the data to be displayed that I had entered previously.

### Additional Context

![{5A5BAB5C-0DCC-446F-B245-F99A0B945E22}](https://github.com/user-attachments/assets/cfa6bc2f-24ca-48f9-9fb3-55cb36b80e69)

### Recommended Priority Level

High

**Comment by cfa-jonathan** [comment]
This should be resolved by the following pull request: https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/101
