### ISSUE TITLE
Admin Career Prep backend

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#107]
Links to Google Sheet design to ensure all fields are collected:
- [WJI Reporting Data](https://docs.google.com/spreadsheets/d/1rIQWcFswHGqT2Gl7W8ObnXdnRwW1eXIe3JxwYM1tJJo/edit?gid=1505172597#gid=1505172597)
- [Career Prep Data Collection](https://docs.google.com/spreadsheets/d/1rIQWcFswHGqT2Gl7W8ObnXdnRwW1eXIe3JxwYM1tJJo/edit?gid=1089650238#gid=1089650238)
- [Admin](https://docs.google.com/spreadsheets/d/1rIQWcFswHGqT2Gl7W8ObnXdnRwW1eXIe3JxwYM1tJJo/edit?gid=1347216247#gid=1347216247)

Using the above to:
- [x] update database
- [ ] create DTOs
- [ ] create server functions
- [ ] create necessary API routes (guarded according to role)

branch here: [career-prep-admin](https://dev.azure.com/CFA1/672c89e5-98e0-4c19-a4fb-809883b04cf6/_git/CoalitionWebsite?version=GBcareer-prep-admin)

Current Schema
> Hot pink tables have not been implemented on local db. Once this has been reviewed will update to dev and test environment.
![Image](https://github.com/user-attachments/assets/afc76e16-1d36-446d-b20d-3ab2d8979687)

**Comment by theGaryLarson** [comment]
@not-damien Just a reminder that Bethany and Dinah need to be able to view the Assessment results as well. Please make this a component so that we can show the results to the Jobseekers on their Dashboard in the future.

**Comment by not-damien** [comment]
On it should be ready by friday
