### ISSUE TITLE
Video Upload - No Preview or Link Validation

### ISSUE THREAD

**Issue by bethanyvasquez** [Computing-For-All/nextjs-issue-tracker#109]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Not sure

### Issue Description

No video validation or preview.

When you click "enter" after pasting the link, it progresses to the next page.

When you select the "previous" button to navigate back to the previous page, the information you submitted does not save (skills, etc.).

### URL of the Page

https://www.watechwfcoalition.org/edit-profile/jobseeker/showcase

### Git commit hash shown on the site

a95009e

### Steps to Reproduce

https://www.watechwfcoalition.org/edit-profile/jobseeker/showcase 

### Recommended Priority Level

None

**Comment by theGaryLarson** [comment]
@not-damien  I know you got this working previously. Is it possible to validate the link before moving forward? Something as simple as startsWith("https://www.youtube.com") may work. Not sure if there is a way to confirm the link is actually to a valid video before allowing submission of the link.

**Comment by not-damien** [comment]
@theGaryLarson I have a link validation function i wrote for the jobseeker showcase/profile page, Ill look into adding that to that page

**Comment by not-damien** [comment]
link validation on branch [video-link-validate](https://dev.azure.com/CFA1/672c89e5-98e0-4c19-a4fb-809883b04cf6/_git/CoalitionWebsite?version=GBvideo-link-validate)

**Comment by theGaryLarson** [comment]
LGTM Closed
