### ISSUE TITLE
Editing Profile - Enrollment Status reset

### ISSUE THREAD

**Issue by bethanyvasquez** [Computing-For-All/nextjs-issue-tracker#111]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Not sure

### Issue Description

I created my profile. Looked at Profile page. Selected Edit Profile. On the 2nd step, in Education, my enrollment status was reset and I had to reselect the option I previously entered.

### URL of the Page

https://www.watechwfcoalition.org/edit-profile/jobseeker/education

### Git commit hash shown on the site

a95009e

### Steps to Reproduce

https://www.watechwfcoalition.org/edit-profile/jobseeker/education

### Recommended Priority Level

None

**Comment by cfa-jonathan** [comment]
Duplicate of https://github.com/Computing-For-All/nextjs-issue-tracker/issues/102
