### ISSUE TITLE
Editing Profile - Showcase section reset/inputs not saved (Test & Merge #101 Before Me)

### ISSUE THREAD

**Issue by bethanyvasquez** [Computing-For-All/nextjs-issue-tracker#112]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Not sure

### Issue Description

When editing my profile, on the showcase step, none of my previous inputs were saved.

### URL of the Page

https://www.watechwfcoalition.org/edit-profile/jobseeker/showcase

### Git commit hash shown on the site

a95009e

### Steps to Reproduce

https://www.watechwfcoalition.org/edit-profile/jobseeker/showcase

### Recommended Priority Level

None

**Comment by cfa-jonathan** [comment]
This should be resolved by https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/103

**Comment by theGaryLarson** [comment]
LGTM Closed
