### ISSUE TITLE
Editing Profile - Voluntary Disclosure

### ISSUE THREAD

**Issue by bethanyvasquez** [Computing-For-All/nextjs-issue-tracker#113]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Not sure

### Issue Description

When editing profile, on voluntary disclosure section, my ethnicity did not save my previous input. 

### URL of the Page

https://www.watechwfcoalition.org/edit-profile/jobseeker/disclosures

### Git commit hash shown on the site

a95009e

### Steps to Reproduce

https://www.watechwfcoalition.org/edit-profile/jobseeker/disclosures

### Recommended Priority Level

None

**Comment by rorosaurus** [comment]
Can confirm the issue

**Comment by cfa-jonathan** [comment]
This issue is mostly done but blocked by the following issue: https://github.com/Computing-For-All/nextjs-issue-tracker/issues/128

The related code is in this branch: https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite?version=GBjobseeker-fix-disclosures-page-autoload

**Comment by cfa-jonathan** [comment]
This should be ready for testing at this pull request: https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/105

This ticket is related to the following ticket: https://github.com/Computing-For-All/nextjs-issue-tracker/issues/128

Ticket 128 will likely need to be merged in before autoload can be fully tested.
