### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by dharam9610** [Computing-For-All/nextjs-issue-tracker#115]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Bug

### Issue Description

Unable to fill-in the Location field. Had to skip that page to complete the profile creation.

### URL of the Page

https://www.watechwfcoalition.org/services/employers/dashboard

### Git commit hash shown on the site

a95009e

### Steps to Reproduce

Begin to create a new employer profile and navigate to the screen with the field: Location

### Additional Context

OS: Mac Seqouia 15.0
Browser: Safari

### Recommended Priority Level

High

**Comment by theGaryLarson** [comment]
When adding locations on company page it does update the professional experience work location drop-down.
Mac Seqouia 15.0
Safari

**Comment by quincyp** [comment]
MacOS Sonoma 14.6.1

Working as expected on Firefox and Google Chrome. 
Confirmed, not working on Safari as well during my testing.

TypeError: options.map is not a function. (In 'options.map((option)=>/*#__PURE__*/ (0, {imported module ...

app/ui/components/mui/SelectAutoload.tsx (112:25) @ SelectAutoload

Will update after some more testing/troubleshooting

**Comment by quincyp** [comment]
Now working on Safari as well on my end @dharam9610 could you confirm if this has been resolved on your end as well?

**Comment by theGaryLarson** [comment]
closing this. will merge into test env upon integration of all uat fixes.
