### ISSUE TITLE
Disallow arbitrary options to be input on education page and company page

### ISSUE THREAD

**Issue by gageberz** [Computing-For-All/nextjs-issue-tracker#118]

**Comment by theGaryLarson** [comment]
Which branch is this in? Is it in main? Not sure what I'm looking for to review.

**Comment by gageberz** [comment]
The branch no longer exists. I thought an alternative implementation was done for education page and company page already disallows it iirc. Will test this out tomorrow morning.

Thank you,
Gage

-------- Original Message --------

**Comment by gageberz** [comment]
Can confirm that employer company page disallows arbitrary options, as for the jobseeker education page: https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/114
This suggests that we want arbitrary options.
