### ISSUE TITLE
Home Page | Hydration Error

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#119]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Bug

### Issue Description

Hydration error on loading of page. I believe this happened when merging the Careers pages into main.

![{5F40B2D2-C42A-4A37-9606-590B13BC2BEC}](https://github.com/user-attachments/assets/103a92e0-b9e9-4974-ba0d-291e32c2050b)

![{A4E804EF-672B-4376-9E0F-68BEB985656A}](https://github.com/user-attachments/assets/48f6bad2-7459-4fee-b43d-207a88e0c099)

### URL of the Page

https:watechcoalition.org

### Git commit hash shown on the site

a95009e

### Steps to Reproduce

1. Load up the home page

### Expected Behavior

Not get a hydration error.

### Recommended Priority Level

None

**Comment by rorosaurus** [comment]
Gary identified the issue and fixed it with a server restart :)
