### ISSUE TITLE
Create training provider pages

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#120]

**Comment by rorosaurus** [comment]
And the carousel / card component to preview them at the bottom of each career page

**Comment by rorosaurus** [comment]
Figma Link (Desktop): https://www.figma.com/design/sVcYXvhUH664gAu7KfKu01/Careers?node-id=2031-1078&t=CqS5kaVEPAz9X1j9-4

**Comment by rorosaurus** [comment]
Training program pages created in PR 151. Next is the card component!

**Comment by rorosaurus** [comment]
Cards completed. PR 151 merged
