### ISSUE TITLE
Skip Button - Job Seeker Profile form - Step 2

### ISSUE THREAD

**Issue by LLikely** [Computing-For-All/nextjs-issue-tracker#122]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Bug

### Issue Description

Clicking the skip button takes me out of the form completely rather than advancing to Step 3.

### URL of the Page

https://www.watechwfcoalition.org/edit-profile/jobseeker/education

### Git commit hash shown on the site

unknown

### Steps to Reproduce

1. Login or Create Account as Job Seeker
2. Complete Profile form Step 1
3. Skip Step 2

### Expected Behavior

A skip button should skip the step shown rather than skipping the rest of the form altogether.

### Recommended Priority Level

Medium

**Comment by quincyp** [comment]
Update: this has been updated and implemented for all pages on my branch, done for both jobseekers and employers as they share the same layout/component; pull request to main branch has no merge conflicts, but had an Azure error on a required test, re-queued for now, but I will need to continue tomorrow

@theGaryLarson unsure if we came to a conclusion on an alert to users about unsaved data when leaving a page? I recall talking about it in a previous meeting and adding it to a task, but I can't seem to find the task on this board? At the moment it will instantly take you to the next page without a warning of unsaved data for any fields they may have input

**Comment by theGaryLarson** [comment]
LGTM Closed!
