### ISSUE TITLE
Job Seeker Profile - Reorder Form Steps

### ISSUE THREAD

**Issue by LLikely** [Computing-For-All/nextjs-issue-tracker#123]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Content

### Issue Description

UX issue. Lower the user bounce rate by putting the fun and easy sections of the form first. Users are motivated to get in front of employers, but less motivated to do the drudgery of detailing education and work experience, (more likely to skip).

### URL of the Page

https://www.watechwfcoalition.org/edit-profile/jobseeker/education

### Git commit hash shown on the site

ubknown

### Steps to Reproduce

1. Create new account as Job Seeker
2. Begin filling out profile creation form

### Expected Behavior

Step 1 - Current as is: **Profile Settings**
Step 2 - Move current step 5 here, **what are you looking for and role/pathway**
Step 3 - Move current step 4 here, **Showcase information**
Step 4 - Move current step 2 here, **Education**
Step 5 - Move current step 3 here, **Work Experience**
Step 6 - Current as is:  **Disclosures and permissions**

### Recommended Priority Level

Medium

**Comment by theGaryLarson** [comment]
LGTM Closed!
