### ISSUE TITLE
Jobseeker Profile Disclosures Page - Database Modifications

### ISSUE THREAD

**Issue by cfa-jonathan** [Computing-For-All/nextjs-issue-tracker#128]
The following changes are needed in the JsDisclosuresDTO, JsDisclosuresPostDTO, and the Prisma Model for jobseekers_private_data:

### jobseekers_private_data Prisma Model
- Field: disability
    - Default Value: ""
    - Should Contain: The type of disability the user selected after selecting they have a disability.
- New Field: disability_status
    - Default Value: ""
    - Should Contain: "yes", "none", "undisclosed" depending on how they indicate having a disability or not.
- Field: is_veteran
    - Default Value: ""
- Field: gender
    - Default Value: ""
- Field: race
    - Default Value: ""
- Field: ethnicity
    - Default Value: ""
- Field: is_authorized_to_work_in_usa
    - Default Value: NULL
    - Should Contain: True, False, but should be NULL to begin with so when the values retrieved from the database are done when loading the page, if they haven't selected True or False yet, we are able to tell.
    - Additional Note: Should probably add a comment indicating that this field should be required by the frontend; so that it is not accidentally made optional in the future if referring to the prisma.schema as an indication.
- Field: job_sponsorship_required
    - Default Value: NULL
    - Should Contain: True, False, but should be NULL to begin with so when the values retrieved from the database are done when loading the page, if they haven't selected True or False yet, we are able to tell.
    - Additional Note: Should probably add a comment indicating that this field should be required by the frontend; so that it is not accidentally made optional in the future if referring to the prisma.schema as an indication.

### _JsDisclosuresDTO_
- _Field: hasDisability_
    - _Currently: Gets set with the Disability Type stored in the database._
    - _Should: Be changed to "disability" to match the database field._
- _New Field: disabilityStatus_
    - _Should: Be an optional string|null type to match the other DTO fields, and set to the disability_status field from the database_

### _JsDisclosuresPostDTO_
- _New Field: disabilityStatus_
    - _Should: Be a required string type_

**Comment by cfa-jonathan** [comment]
This is blocking the following issue: https://github.com/Computing-For-All/nextjs-issue-tracker/issues/113

You can find the mostly-complete code in this branch: https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite?version=GBjobseeker-fix-disclosures-page-autoload

The DTOs and API get and upsert routes have been updated with the needed changes, but with the database references commented out. When the database is updated, the commented out pieces can be swapped in.

When the database is updated, make sure to inform me that the blocked issue can be completed.

**Comment by theGaryLarson** [comment]
updated and informed/discussed with jonathan via  teams chat
