### ISSUE TITLE
App Crashes when you skip selecting a company as an employer

### ISSUE THREAD

**Issue by not-damien** [Computing-For-All/nextjs-issue-tracker#129]
will be unblocked with https://github.com/Computing-For-All/nextjs-issue-tracker/issues/134

**Comment by not-damien** [comment]
fix is on admin branch

**Comment by theGaryLarson** [comment]
This fixes the error but the following page gets stuck on loading company locations. This should be resolved by Quincy's update in issue
https://github.com/Computing-For-All/nextjs-issue-tracker/issues/134
