### ISSUE TITLE
Employer | Account Creation Updates - Consolidate into single page

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#134]
- [x] Update company page. Do not show company details
- [x] Fix Progress steps should be total of 3
- [x] Make DOB and phone number optional.
- [ ] Disclosures Page: Not loading the following fields: job title, linkedin url, work location

**Comment by quincyp** [comment]
Completed:

- Update company page. Do not show company details
- Fix Progress steps should be total of 3
- Make DOB and phone number optional.

Merged to main.

As for disclosures page, we can talk about it in a call, but to summarize:

- edit: clarified in call, behavior as input is as expected, should NOT pull from job_listings

**Comment by quincyp** [comment]
Update: 
- after pulling from main now able to reproduce error TypeError: options.map is not a function
- appears to be issue where from company page useUpdateSession is not updating
![Image](https://github.com/user-attachments/assets/823ff5fc-c443-48a3-a537-5553659a349b)


- on disclosures page we use session.user.companyId in 2 places and companyId is null causing the above noted error, able to resolve by using companyId from redux store, but concerning unable to figure out why session is not updating as expected

**Comment by theGaryLarson** [comment]
We discussed but for the sake of record keeping. The decision was to use redux store until we can figure out a way to make updateSesisonProperties reliable.

**Comment by theGaryLarson** [comment]
This issue was made redundant by combining everything for employer profile creation into one page. Also resolved the following issues: #129, #62,  #69, #98,  and #115,.
