### ISSUE TITLE
Jobseeker Profile Create / Edit Text Copy Changes

### ISSUE THREAD

**Issue by cfa-jonathan** [Computing-For-All/nextjs-issue-tracker#136]
Apply changes to the text copy for jobseeker profile creation / modification.

- [x] Introduction page
- [x] Education page
- [x] Work experience page
- [x] Showcase page
- [x] Preferences page
- [x] Disclosures page

**Comment by cfa-jonathan** [comment]
Currently waiting for Lynn to complete copy edits for Preferences and Disclosures pages.

**Comment by cfa-jonathan** [comment]
This has been completed with this pull request: https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/108

**Comment by theGaryLarson** [comment]
LGTM Closed
