### ISSUE TITLE
Jobseeker | Remove agree to terms at end of Profile Creation.

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#137]
The terms are agreed to at the beginning. Do not need to ask 2x.

- [x] Remove terms from disclosures page
- [x] update DTOs accordingly
- [x] update API routes accordingly

**Comment by cfa-jonathan** [comment]
This should be completed by pull request: https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/109
