### ISSUE TITLE
App Crashed when creating employer

### ISSUE THREAD

**Issue by not-damien** [Computing-For-All/nextjs-issue-tracker#138]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Bug

### Issue Description

![runtimeError](https://github.com/user-attachments/assets/b4ebb6f8-dd1a-4ada-8437-8a883406067c)

### URL of the Page

https://www.watechwfcoalition.org/edit-profile/employer/disclosures

### Git commit hash shown on the site

7817033

### Steps to Reproduce

create an employer account 
try to add a company

### Recommended Priority Level

High

**Comment by theGaryLarson** [comment]
The session is not guaranteed to update which was causing the error. The API in the work location component was leveraging session.user.companyId.

Fix: Used redux store instead to get the data

Fix is merged into main but was implemented in this [branch](https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite?version=GBfix-employer-account-creation).
