### ISSUE TITLE
Job Seeker Profile video auto-play

### ISSUE THREAD

**Issue by LLikely** [Computing-For-All/nextjs-issue-tracker#139]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Enhancement

### Issue Description

UX issue. Disable autoplay of video on user profile. Presents an annoyance to user and requires pressing stop.

### URL of the Page

https://www.watechwfcoalition.org/services/jobseekers/7dc116e6-1a24-4a52-8f73-868383578371

### Git commit hash shown on the site

ubknown

### Steps to Reproduce

Visit profile with video while logged in.

### Expected Behavior

Autoplay behavior should only occur in certain expected contexts.

### Recommended Priority Level

Medium

**Comment by theGaryLarson** [comment]
I don't get auto play behavior. I'm wondering if it is a browser setting.

**Comment by not-damien** [comment]
could be that she is using a mac with safari

**Comment by quincyp** [comment]
completed, embed link now has autoplay=0 appended, appears to work as intended with no autoplay on Firefox and Safari for me.
