### ISSUE TITLE
Complete the resume required check on Showcase edit/create jobseeker profile page

### ISSUE THREAD

**Issue by cfa-jonathan** [Computing-For-All/nextjs-issue-tracker#150]

**Comment by theGaryLarson** [comment]
@cfa-jonathan  Did someone tell you that resume has to be required? The original discussion with Ritu was that it did not have to be. The reasoning being they may not have one ready for upload. It makes sense to have it required but don't want it to be a barrier to creating an account and getting into Career Prep where they help with resume writing.

**Comment by cfa-jonathan** [comment]
Fixed the autoload of the resume upload. Removed the required status from the field.

This should be completed by this pull request: https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/137
