### ISSUE TITLE
Refactor Bookmarked and Applied Job Postings into a single table. Transform implicit join to explicit.

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#151]
@not-damien I walked through this and think everything is working correctly. I added the jobStatus field to the where clause to filter for Bookmarked and Applied Jobs but this will probably need a bit of a rework based on the Teal info Bethany shared.

branch: https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite?version=GBjob-placement-db-updates

PR: https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/132

**Comment by not-damien** [comment]
Looking it over now

**Comment by not-damien** [comment]
Looks good for now, merging
