### ISSUE TITLE
Careers: Training Provider logo images not showing up

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#152]
Images at the bottom of the page here https://www.watechwfcoalition.org/services/careers/software-developer are not showing

![Image](https://github.com/user-attachments/assets/555c204f-870c-47f1-809b-85ad44d75e0b)

I'm not sure where the "See more" button is supposed to link but its a dead link. We can comment out the button for now.

relates to #120

**Comment by rorosaurus** [comment]
See more now removed. The images won't render if the logo is missing now with PR 151
