### ISSUE TITLE
Jobseeker Work Experience: Required Tooltip not working for startDate

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#154]
@cfa-jonathan This is already in main but the fix is not ideal. It does not take advantage of the custom tooltip formatting you have in place. I couldn't figure out why it works for `endDate` but not for `startDate`. So, I added the required: true attribute on textField slotProps as a temporary fix. I was getting a build error because of type mismatch so I updated workexperience.tsx initial values for startDate from null to undefined but this is where I found it was giving issue.

```typescript

<DatePicker
            label={'Start Date'} // fixme: if adjusted add the asterisk back. setting required renders it automatically.
            views={['month', 'year']}
            value={
              workExperience[classStarts]?.isValid()
                ? workExperience[classStarts]
                : null
            }
            onChange={(val) => handleChange(index, classStarts, val)}
            slotProps={{ textField: { fullWidth: true, required: true } }} // fixme: Required tooltip is not working here. Can submit without entering a startDate. This was the temporary fix to build prod.
          />
```

**Comment by cfa-jonathan** [comment]
This is resolved by pull request: https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/141

Which also includes some other minor and related field fixes.
