### ISSUE TITLE
Jobseeker Education Page - Spacing issue

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#16]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Bug

### Issue Description

The buttons on the bottom of the page are resting against the project experience component. Needs to be spaced out consistently.
![{21CA8844-E53F-4FD5-A967-94CD9948D5AC}](https://github.com/user-attachments/assets/d4b97854-025a-415f-b044-31cb6791aef1)

### URL of the Page

/create-profile/jobseeker/education

### Steps to Reproduce

1. go to the above page
2. scroll to bottom
3. observe (desktop 1920x1080)

### Expected Behavior

consistent spacing

### Additional Context

![{D8A3E85B-8DCB-40F8-AAF2-C99E595A9636}](https://github.com/user-attachments/assets/07f14d44-6cec-4559-aa2f-323475db6309)

### Recommended Priority Level

Medium

**Comment by rorosaurus** [comment]
Fixed!
