### ISSUE TITLE
Update signup/jobseeker page for consistency

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#177]
https://www.watechcoalition.org/signup/jobseeker

- [ ] Should be "Createa TWC account" in all instances
- [ ] Blurb below can be deleted

![Image](https://github.com/user-attachments/assets/c75d3d97-e1a7-4a69-a627-cc9623ca612b)

**Comment by rorosaurus** [comment]
Addressed in PR167
