### ISSUE TITLE
Avatar Image Load

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#18]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Bug

### Issue Description

When changing image on introduction page after initial setting of a new image. It does not properly load to blob storage or display in the image placeholder in the AvatarUpload component.

### URL of the Page

/create-profile/jobseeker/introduction

### Steps to Reproduce

1. Select an initial image to change from the default provided by OAuth provider
2. Finish account creation
3. go back to the above listed page jobseeker create profile introduction.
4. select an image to upload from your computer
5. Image will change briefly and revert back to the originally selected image

### Expected Behavior

Expect the image to change to the new selection and be uploaded to blob storage.

### Additional Context

![{9EAD3465-9D3F-4C4B-A6F3-A944ABE8A386}](https://github.com/user-attachments/assets/2441961e-39c7-4bb3-84dd-fa153cb781bc)

### Recommended Priority Level

Low

**Comment by rorosaurus** [comment]
Can't repro anymore
