### ISSUE TITLE
Replace CFA everywhere

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#19]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Content

### Issue Description

Incorrect Logo in navbar/header

### URL of the Page

/create-profile/jobseeker/introduction

### Steps to Reproduce

1. go to jobseeker profile creation
2. observe logo

### Expected Behavior

WTWC Logo please

### Additional Context

![image](https://github.com/user-attachments/assets/612ab393-085c-473b-8cb6-7022a9c8e664)

### Recommended Priority Level

High

**Comment by rorosaurus** [comment]
I think we talked about removing the "save and log out" link too, and maybe even merging this with the main page header? Thoughts @theGaryLarson ?

**Comment by rorosaurus** [comment]
I can't access the employer routes, but it appears correct for me on the jobseeker page now, so I think it's been updated! Can you confirm, @sdnmcfn ?

**Comment by theGaryLarson** [comment]
Needs verification from Maria.

**Comment by rorosaurus** [comment]
Confirmed fixed
