### ISSUE TITLE
Job listings with filter

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#197]
Need to determine structure of pages with marketing. Meeting Thursday or Friday 12/18 or 12/19

**Comment by gageberz** [comment]
Part 1/X of this was merged in.
I think we talked about wanting a couple more filters, but iirc we need new fields for job listings to be able to. I believe years of experience was discussed, don't recall the others.

@theGaryLarson anything else other than YOE we wanted to add that you know of?
