### ISSUE TITLE
Signed in and tried to sign up again

### ISSUE THREAD

**Issue by sdnmcfn** [Computing-For-All/nextjs-issue-tracker#20]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Bug

### Issue Description

Had signed in and did not complete profile creation. Went back to landing page, was still signed on and Sign up button was visible. Clicked sign up button to go back to profile creation and received under construction page.

### URL of the Page

https://www.watechwfcoalition.org/underconstruction

### Steps to Reproduce

1. Sign in with OAuth
2. Start account profile creation but dont finish it
3. Go back to home page
4. Sign up button appears - press it
5. Error page appears

### Recommended Priority Level

None

**Comment by rorosaurus** [comment]
I think based on a previous discussion with Gary, this is a future external link to sign up for the WTWFC? @theGaryLarson is that correct?
