### ISSUE TITLE
Add language to instruct user to upload to video youtube and provide video link

### ISSUE THREAD

**Issue by not-damien** [Computing-For-All/nextjs-issue-tracker#21]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Content

### Issue Description

In the profile creation flow it currently gives no indication that the video should come from youtube

### URL of the Page

/create-profile/jobseeker/showcase

### Steps to Reproduce

1)create profile

### Recommended Priority Level

Low

**Comment by theGaryLarson** [comment]
@sdnmcfn Language for video upload needs updated here
https://www.figma.com/design/g54drsZOvLMZNvrAIrpJkH/MVP-R2-10%2F07?node-id=146-53649&t=3xpoBkrSIe120aqM-4

**Comment by theGaryLarson** [comment]
Waiting on copy

**Comment by sdnmcfn** [comment]
here is the new copy @not-damien 

https://www.figma.com/design/g54drsZOvLMZNvrAIrpJkH/MVP-R2-10%2F07?node-id=146-50353&t=Sfr5vSrZL4CnOhZU-4


In today’s competitive job market, finding creative ways to elevate your profile is key. A personalized video introduction offers a unique opportunity to showcase your skills, personality, and career goals.

- **Highlight Your Unique Value Proposition**: Share your professional journey, key accomplishments, and why you're a valuable asset to any team.

- **Showcase Your Skills and Expertise**: Demonstrate your technical skills, soft competencies, and how they can benefit your future employers.
 
- **Express Your Career Aspirations**: Articulate your long-term career goals and how you see yourself growing professionally.

Upload your video URL below and elevate your profile.
