### ISSUE TITLE
Incorrect redirect after submitting jobseeker/disclosures page

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#22]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Bug

### Issue Description

I should be directed to the congratulations page but rather it is directing me back to the home page.

### URL of the Page

/create-profile/jobseeker/disclosures

### Steps to Reproduce

submit info as a jobseeker on the disclosures page.

### Expected Behavior

directed to the `/create-profile/jobseeker/congratulations` page

### Recommended Priority Level

Urgent

**Comment by rorosaurus** [comment]
merged into main :)
