### ISSUE TITLE
Updated Footer Design

### ISSUE THREAD

**Issue by sdnmcfn** [Computing-For-All/nextjs-issue-tracker#23]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Enhancement

### Issue Description

Updated footer across all different sizes. Updated figma page is here: https://www.figma.com/design/jofo53C0PWZ0SV8dPZZ1Sv/Design-System?node-id=4071-458

### URL of the Page

entire site

### Steps to Reproduce

N/A

### Recommended Priority Level

None

**Comment by rorosaurus** [comment]
![Image](https://github.com/user-attachments/assets/7b1e71f0-ba21-48a5-bae4-21fc86552b83)

I think the centered LinkedIn part is a little off center? Just me?

**Comment by not-damien** [comment]
it is, ill add a fix for that

**Comment by not-damien** [comment]
Should be good now

**Comment by rorosaurus** [comment]
Looks great! Thank you!
