### ISSUE TITLE
Work address location dropdown does not populate and is unable to be submitted

### ISSUE THREAD

**Issue by not-damien** [Computing-For-All/nextjs-issue-tracker#30]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Not sure

### Issue Description

Work address location dropdown does not populate and is unable to be submitted
![Capture](https://github.com/user-attachments/assets/b525e310-7b40-477b-a548-d0ca9069f113)

### URL of the Page

https://watechwfcoalition.org/create-profile/employer/disclosures

### Steps to Reproduce

1) signup as a employer and follow each step in the flow
2) fill out new company info 
3)on last page attempt to add work location 

### Recommended Priority Level

Medium

**Comment by not-damien** [comment]
This error was also in the server console
![Capture2](https://github.com/user-attachments/assets/72a1af36-723d-49fc-bab5-ed7a8ca8c066)

**Comment by theGaryLarson** [comment]
This is being resolved in my current branch. The work address will be removed from here and locations are to be added to the company creation page.

**Comment by quincyp** [comment]
Completed, merged to main, ready for review
