### ISSUE TITLE
Remove mark for deletion on profile complete

### ISSUE THREAD

**Issue by rorosaurus** [Computing-For-All/nextjs-issue-tracker#31]
### Duplicate Check

- [x] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Enhancement

### Issue Description

After finishing profile-create/edit wizard, remove the user's mark for deletion

### URL of the Page

profile-create/*/congratulations

### Steps to Reproduce

1. Reach create-profile/*/congratulations page

### Recommended Priority Level

None

**Comment by theGaryLarson** [comment]
Related Items I will handle:

deleteUser() server side function
unflagForDeletion() api route/server side function

**Comment by theGaryLarson** [comment]
Relates to #44

**Comment by theGaryLarson** [comment]
in main api/jobseeker/validate-profile  calls server function unflagDeletion()
