### ISSUE TITLE
Assign Jobseeker/Employer ID on role set (after verification)

### ISSUE THREAD

**Issue by rorosaurus** [Computing-For-All/nextjs-issue-tracker#45]
### Duplicate Check

- [x] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Enhancement

### Issue Description

Ensure a Jobseeker ID or Employer ID are created when the role is set.

### URL of the Page

signup/jobseeker and signup/employer

### Steps to Reproduce

After qualifying for the selected role, when we set the role, also set the Jobseeker or Employer ID.

### Recommended Priority Level

Medium

**Comment by theGaryLarson** [comment]
@rorosaurus  I can do this but think i should probably wait until you have your refactor of signin process including the initial screening in place. Essentially we just need to call updateSessionProperties hook at the point where ROLE is converted from GUEST to one of the other and update session with a generated uuidv4.
