### ISSUE TITLE
Create Jobseeker Dashboard page

### ISSUE THREAD

**Issue by rorosaurus** [Computing-For-All/nextjs-issue-tracker#46]
### Duplicate Check

- [x] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Content

### Issue Description

Page is blank right now

### URL of the Page

/services/jobseeker/dashboard

### Steps to Reproduce

1. Create jobseeker profile, skip setup

### Recommended Priority Level

Medium

**Comment by theGaryLarson** [comment]
Waiting on Design

Design:
https://www.figma.com/design/mBQcgzuSbYgpGGUVs4tE8C/Job-Candidate?node-id=32-12081&node-type=canvas&t=hGjR9bzW5GGrhoq9-0

https://computinforall.sharepoint.com/:w:/s/ProjectManagement/Eb8-sigbf9hBqzMNaWkNgagB1GF1irxhe3RJcOWB41N-RA?e=BbaMP5
