### ISSUE TITLE
Employer Landing Page Design

### ISSUE THREAD

**Issue by sdnmcfn** [Computing-For-All/nextjs-issue-tracker#51]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Content

### Issue Description

Completed Employer Landing Page can be found here: https://www.figma.com/design/g54drsZOvLMZNvrAIrpJkH/MVP-R2-10%2F07?node-id=60-52113

Desktop (1440px), Mobile (430px, 375px) versions are built for now. Rest screens will be built soon. 

### URL of the Page

https://www.watechwfcoalition.org/services/employers

### Steps to Reproduce

N/A

### Recommended Priority Level

None

**Comment by not-damien** [comment]
Waiting on photos

**Comment by theGaryLarson** [comment]
The Post a Job and Connect with Ease sections had to be removed because these features are not implemented yet. @sdnmcfn  Just want to make sure you are still happy with the way this looks after removing it in main for release.
