### ISSUE TITLE
Typo in skip profile link on profile-creation for employers currently redirects to "/services/employer/dashboard" but needs to redirect to "/services/employers/dashboard"

### ISSUE THREAD

**Issue by not-damien** [Computing-For-All/nextjs-issue-tracker#56]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Bug

### Issue Description

Typo in skip profile link on profile-creation for employers currently redirects to "/services/employer/dashboard" but needs to redirect to "/services/employers/dashboard"

### URL of the Page

/create-profile/employer/personal

### Steps to Reproduce

1) go to edit your profile as an employer
2) click skip button

### Recommended Priority Level

None

**Comment by rorosaurus** [comment]
Fixed in PR62
