### ISSUE TITLE
Move listview page  "/services/employers/dashboard/listview"  to have a shorter path something like "/services/listview" or "/services/talent-search"

### ISSUE THREAD

**Issue by not-damien** [Computing-For-All/nextjs-issue-tracker#57]
Was discussed very early on that this page should have a shorter url and not be under the employer dashboard. 

After moving the page into the new directory please verify all imports and links to page are still functional

**Comment by theGaryLarson** [comment]
i like services/talent-search

**Comment by rorosaurus** [comment]
Looks good!
