### ISSUE TITLE
Jobseeker Education Page: Data not loading

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#58]
- [x] Stored projects not loading
- [x] Stored education not loading
- [x] Certification expiration date is same as issue date

**Comment by cfa-jonathan** [comment]
Stored data not loading is fixed on my branch but not merged into main yet. Will look into certification expiration date issue.

**Comment by cfa-jonathan** [comment]
Fixed certification expiration date being same as issue date. Not merged into main yet.
