### ISSUE TITLE
Jobseeker Work Experience Page: radio buttons not displaying existing options.

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#68]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Bug

### Issue Description

![{F94A6ED0-5BB4-45F3-8A4B-4C87787B9E8B}](https://github.com/user-attachments/assets/8d15ea8c-8e9c-4f5b-83b9-a0d2fda14137)

Validated the data does exist in the database
![{B1DFB11D-7E0E-48EB-92E8-F17E18CBE870}](https://github.com/user-attachments/assets/af0e9ee6-8f35-4232-b35d-fedb9fb0ba1b)

### URL of the Page

/create-profile/jobseeker/work-experience

### Steps to Reproduce

1.  Complete work experience information
2.  Save and continue.
3.  Navigate back to the page (triggering useEffect here requires adding pathname to useEffect dependency array)
4.  Refresh to trigger useEffect

### Expected Behavior

Radio buttons to be filled based on database record as seen in image below:
![{EC71A8AA-4785-4838-9AFC-7633555CB398}](https://github.com/user-attachments/assets/e43b4d8e-c7e7-4016-840a-bde0df062c37)

### Recommended Priority Level

High

**Comment by cfa-jonathan** [comment]
Fixed in my branch, not merged to main yet.
