### ISSUE TITLE
Employer Company Info Page: New company issue

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#69]
Trying to create a new company doesn't work

- [ ] no companyId is passed to the api route
> I believe it may be trying to use the redux store if there was an existing company.
- [ ] The company store data needs reset if an user selects an existing company. Then enters a new company
- [ ] Ensure new company info is saved to redux store and the new companyId is saved to session
- [ ]  Work Locations input needs added and passed to the api as an array of zipCodes. Granularity of location is 5 digit zip code.

**Comment by quincyp** [comment]
Did a review these all appear to work on forms and update the database.

 

- [x] no companyId is passed to the api route

- [x] The company store data needs reset if an user selects an existing company. Then enters a new company. NOTE: the user can enter a new company, however the sector dropdown does not pop up until they click off the field

- [x] Ensure new company info is saved to redux store and the new companyId is saved to session NOTE: This appears to save and pull correctly, however I am not sure there is additional testing or edge cases I may have not checked

- [x] Work Locations input needs added and passed to the api as an array of zipCodes. Granularity of location is 5 digit zip code.
