### ISSUE TITLE
Displaying Jobseeker Current Education Logic

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#75]
see pull request on Azure for details
https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/53

TLDR: Had to add enrollment status to jobseekers_education. It will replace jobseekers_education.is_enrolled.
It is functional and working but did not want to remove the boolean bcs I remember you two had done some logic to display the currently enrolled school.

**Comment by rorosaurus** [comment]
addressed with PR59
