### ISSUE TITLE
Jobseeker Profile Creation: Ensure input requirements match DB

### ISSUE THREAD

**Issue by rorosaurus** [Computing-For-All/nextjs-issue-tracker#77]
GPA is required, but not labelled as such.

Also, GPA shouldn't be required if not actively enrolled for some time, right?

**Comment by theGaryLarson** [comment]
It should not be required. Is optional on the database. @cfa-jonathan  can you do a pass on jobseeker profile creation pages to ensure input requirements align with the database?

**Comment by cfa-jonathan** [comment]
_This comment in process of being created_

- [x] Introduction Page performs:
    - [x] User change
        - Related Required User Fields: email
        - Related Optional User Fields: birthdate, first_name, last_name, phone, phoneCountryCode, photo_url, zip
    - Jobseekers change (which shouldn't be the case anymore; so no apparent reason to match against it)
- [x] Education Page performs:
    - [x] Jobseekers change
        - Related Required Jobseekers Fields: is_enrolled_ed_program 
        - Related Optional Jobseekers Fields: highest_level_of_study_completed
    - [x] Certificates change
        - Related Required Certificates Fields: name, issuingOrg
        - Related Optional Certificates Fields: credentialId, credentialUrl, issueDate, expiryDate, description
    - [x] JobseekersEducation change
        - Related Required JobseekersEducation Fields: id, edLevel, isEnrolled, enrollmentStatus, startDate, gradDate
        - Related Optional JobseekersEducation Fields: preAppEdSystem, degreeType, programId, gpa, description
    - [x] ProjectHasSkills change
        - Related Required ProjectHasSkills Fields: skill_id
        - Related Optional ProjectHasSkills Fields: 
    - [x] ProjectExperiences change
        - Related Required ProjectExperiences Fields: projTitle, projectRole, startDate, completionDate, problemSolvedDescription, teamSize
        - Related Optional ProjectExperiences Fields: repoUrl, demoUrl
- [x] Work Experience Page performs:
    - [x] Jobseekers change
        - Related Required Jobseekers Fields: 
        - Related Optional Jobseekers Fields: years_work_exp, months_internship_exp
    - [x] JobseekersPrivateData change
        - Related Required JobseekersPrivateData Fields: is_authorized_to_work_in_usa, job_sponsorship_required
        - Related Optional JobseekersPrivateData Fields: 
    - [x] WorkExperience change
        - Related Required WorkExperience Fields: company, jobTitle, isCurrentJob, startDate, responsibilities, isInternship
        - Related Optional WorkExperience Fields: endDate, techAreaId, sectorId
- [x] Showcase Page performs:
    - [x] Jobseekers change
        - Related Required Jobseekers Fields: jobseeker_has_skills
        - Related Optional Jobseekers Fields: intro_headline, portfolio_url, portfolio_password, video_url, resume_url
- [x] Preferences Page performs:
    - [x] Jobseekers change
        - Related Required Jobseekers Fields: 
        - Related Optional Jobseekers Fields: employment_type_sought, targeted_pathway
- [x] Disclosures Page performs:
    - [x] User change
        - Related Required User Fields: has_agreed_terms
        - Related Optional User Fields: 
    - [x] JobseekersPrivateData change
        - Related Required JobseekersPrivateData Fields: is_veteran, disability, gender, race, ethnicity
        - Related Optional JobseekersPrivateData Fields:

**Comment by cfa-jonathan** [comment]
This is related to the following pull request: [https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/98](https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/98)

The frontend UI has been updated to match what is actually required by the DB. The fields are matched against the data retrieved and entered in the comment above.

### Known Issues
- Some Material UI components don't have a default validator; so they will need to be tied to an Error prompt like the one that occurs on the Disclosures page when the Terms are not accepted. A new issue was created for this here: [https://github.com/Computing-For-All/nextjs-issue-tracker/issues/127](https://github.com/Computing-For-All/nextjs-issue-tracker/issues/127) 
- The disclosures page has default values set for all the fields already; so there no way to completely test the required validations. A new issue was created for this here: [https://github.com/Computing-For-All/nextjs-issue-tracker/issues/128 ](https://github.com/Computing-For-All/nextjs-issue-tracker/issues/128 )
