### ISSUE TITLE
Build Training Provider Landing Page

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#94]
#### Marketing
-  Share Benefits of Coalition for TP:
     - Tell employers who are providers are
     -  what they are about
     - what type of candidates they work with
     - browse/recruit candidates that are in need
     - employers connect directly with you for better promoting TP members.
     - interested in becoming a member of coalition CONTACT US!

##### Functionality
- Recruitment to move jobseeker candidates from not job ready to job ready
-  Skills Gap Analysis between job postings and TP programs

### Features

- Have graduates/enrolled students exposed to more employment opportunities
- Edit TP page
- Ability to browse jobseekers in need of training (i.e. pool3 - Not Job Ready)
- Associate Lightcast skills with training programs
-  Employers can view jobseekers filtered by TP  and their programs

#### Future
- Employers able to connect to training providers (internal messaging)

**Comment by sdnmcfn** [comment]
This is now on hold/cancelled. Superseded by new Careers Landing Page
